{{- if .Values.apiManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vircadia-world.apiManager.fullname" . }}
  labels:
    {{- include "vircadia-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-manager
spec:
  type: {{ .Values.apiManager.service.type }}
  ports:
    - port: {{ .Values.apiManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vircadia-world.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-manager
{{- end }} 