{{- if .Values.pgweb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vircadia-world.pgweb.fullname" . }}
  labels:
    {{- include "vircadia-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgweb
spec:
  type: {{ .Values.pgweb.service.type }}
  ports:
    - port: {{ .Values.pgweb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vircadia-world.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgweb
{{- end }} 