{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vircadia-world.postgresql.fullname" . }}
  labels:
    {{- include "vircadia-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "vircadia-world.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }} 