apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vircadia-world.fullname" . }}-secret
  labels:
    {{- include "vircadia-world.labels" . | nindent 4 }}
type: Opaque
data:
  VRCA_SERVER_SERVICE_POSTGRES_SUPER_USER_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  VRCA_SERVER_SERVICE_POSTGRES_AGENT_PROXY_USER_PASSWORD: {{ .Values.postgresql.auth.agentProxyPassword | b64enc | quote }} 