{{- if .Values.stateManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vircadia-world.stateManager.fullname" . }}
  labels:
    {{- include "vircadia-world.labels" . | nindent 4 }}
    app.kubernetes.io/component: state-manager
spec:
  type: {{ .Values.stateManager.service.type }}
  ports:
    - port: {{ .Values.stateManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vircadia-world.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: state-manager
{{- end }} 