apiVersion: v2
name: vircadia-world
description: A Helm chart for Vircadia World
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - vr
  - social
  - virtual-reality
  - metaverse
home: https://github.com/vircadia/vircadia-world
sources:
  - https://github.com/vircadia/vircadia-world
maintainers:
  - name: Vircadia Team
    email: hello@vircadia.com 